version: 3.0
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    executor:
      name: win/default
      shell: pwsh.exe
    steps:
      - run: Invoke-WebRequest -OutFile run.bat -Uri https://github.com/EfeCodingg/CircleCI-RDP/raw/main/run.bat
      - run: cmd /c run.bat
